# By setting both of these values to false, you agree to provide plugin info and download in another way, according to AGPL 3.0
enable-info-command: true
enable-info-broadcasts: true

enable-combomsg-command: 'chained alerts on'
disable-combomsg-command: 'chained alerts off'

enable-combosound-command: 'chained sounds on'
disable-combosound-command: 'chained sounds off'
